server:
  port: 9090

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_schema: ${SCHEMA_NAME:kyc}
        format_sql: ${KYC_LOG_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false